### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by fazhang-master** [AlexanderKroll/kcat_prediction_function#3]
Step 1/3: Calculating numerical representations for all substrates and products.
Step 2/3: Calculating numerical representations for all enzymes.
.....2(a) Loading ESM-1b model.
Traceback (most recent call last):
  File "F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\pyqt1.0.py", line 76, in <module>
    df = kcat_predicton(substrates = substrates,
  File "F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\kcat_prediction.py", line 26, in kcat_predicton
    df_enzyme = calcualte_esm1b_ts_vectors(enzyme_list = enzymes)
  File "F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\enzyme_representations.py", line 38, in calcualte_esm1b_ts_vectors
    model, alphabet = esm.pretrained.load_model_and_alphabet_core(model_data, regression_data)
  File "I:\conda\envs\DLKcat\lib\site-packages\esm\pretrained.py", line 190, in load_model_and_alphabet_core
    if model_name.startswith("esm2"):
AttributeError: 'dict' object has no attribute 'startswith'

**Comment by AlexanderKroll** [comment]
Did you check that you are using the right version of the esm package (fair-esm 0.4.0) as specified on the Readme page?
